baseURL = "https://blog.furan.vip/"
languageCode = "zh-cn"
title = "fuRan's Code"
theme = "fuji"
hasCJKLanguage = true
enableGitInfo = true

[outputFormats]
  [outputFormats.SearchIndex]
    isPlainText = true
    notAlternative = true
    mediaType = "application/json"
    path = "/search/"

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Search"
    url = "/search/"
    weight = 2

  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/NgeKaworu"
    weight = 1

[params]
  showToc = true
  subTitle = "皆無は真実、万事が許す。"
  showWordCounter = true
  showReadTime = true
  math = true
  description = "宓冉的技术博客，专注前端、大前端、微前端。"

[markup]
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content
[markup.highlight]
  codeFences = true  # Disable Hugo's code highlighter
  lineNos = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3