version: '3.9'

services:
  blog-hugo:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: ngekaworu/blog-hugo
    container_name: blog-hugo
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    driver: bridge
